<?php $this->load->view('part/_brain'); ?>
<?php $this->load->view('part/_session'); ?>
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<!DOCTYPE html>
<html lang="en">
    <head>
		<title>Setup C</title>
		
		<?php $this->load->view('part/_header'); ?>
		
	</head>
    <body>
        
		<?php $this->load->view('part/_navi'); ?>
        
        <div class="container">
			<div class="row">
                <div class="col-md-12">
                    <h3>Open tickets</h3>
					<div class="table-responsive">
						<table class="table table-striped table-sm" id="userList">
							<thead>
								<tr>
									<th>#</th>
									<th class="hidden-xs">create</th>
									<th class="hidden-xs">last check</th>
									<th></th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								<?php								
									$query = $this->db->query('SELECT id, num, createdate, lastlog, waiting FROM ticket WHERE status = 0 AND user = '.$this->session->id.'');
									foreach ($query->result() as $row)
									{
								?>
								<tr>
									<th scope="row">
									<?php
										if($row->waiting == 1){ echo '<span style="color: orange">'.$row->num.'</span>'; }elseif($row->waiting == 0){ echo '<span>'.$row->num.'</span>'; }
									?>
									</th>
									<td class="hidden-xs"><?php echo $row->createdate; ?></td>
									<td class="hidden-xs"><?php echo $row->lastlog; ?></td>
									<td>
										<form method="post" action="<?php echo base_url() ?>user-ticket">
											<input type="text" name="ticketTriger" hidden="hidden" value="<?php echo $row->id; ?>">
											<input type="submit" name="trigerTicket" class="btn btn-primary btn-xs" value="view">
										</form>
									</td>
									<td>
										<form method="post">
											<input type="text" name="ticketClose" hidden="hidden" value="<?php echo $row->id; ?>">
											<input type="submit" name="closeTicket" class="btn btn-success btn-xs" value="close ticket">
										</form>
									</td>
								</tr>
								<?php
									}
								?>
							</tbody>
						</table>
					</div>
                </div>
            </div>
			
			<?php
				$query = $this->db->query('SELECT COUNT(*) AS tic FROM ticket');
				$row = $query->row();
				$date = date('Ymd');
			?>
			
            <div class="row">
                <div class="col-md-12">
                    <div class="ticket-number">
                        <h3>Create new ticket <?php echo '#0'.$row->tic.$date; ?></h3>
                        <i><small>(ticket number / autogenerated)</small></i>
                    </div>
                </div>
            </div>
            <div class="vertical-space"></div>
            <div class="row">
                <div class="col-md-12">
                    <form action="" method="post" enctype="multipart/form-data" action="">
                        <div class="form-group">
                            <label for="segment">Segment</label>
                            <select id="segment" class="form-control" name="segment">
                                <option disabled="disabled" selected="selected">---</option>
                                <option value="mail">mail</option>
                                <option value="hosting">hosting</option>
                                <option value="domain">domain</option>
                                <option value="billing">billing</option>
                                <option value="seo">seo</option>
                                <option value="website">website</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="description">Problem description</label>
                            <textarea class="form-control" id="description" name="description" rows="15"></textarea>
                        </div>
                        <div class="form-group">
                            <input type="file" id="image" name="image">
                            <p class="help-block">If you have image of issues, please input them.</p>
                        </div>
                        <button type="submit" class="btn btn-primary" name="createTicket">Send</button>
                    </form>
                </div>
            </div>
    
        </div>
        
        <?php $this->load->view('part/_modal'); ?>
        
        <div class="vertical-space">&nbsp;</div>
		
		<?php $this->load->view('part/_footer'); ?>
		
    </body>
</html>